require 'user.keymaps'
require "user.impatient"
require 'user.lsp'
require 'user.cmp'
require 'user.plugins'
require 'user.gitsign'
require "user.comment"
require 'user.autopairs'
require "user.telescope"
require "user.treesitter"
require 'user.colorscheme'
require 'user.nvim-tree'
require 'user.null-ls'
require 'user.lualine'
require "user.toggle-term"
require "user.escape"
require "user.navigator"
require 'user.options'
require 'user.bufferline'
